# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"

title                    : "Muhammad Kashif"
title_separator          : "-"
name                     : &name "Muhammad Kashif"

description              : &description "Muhammad Kashif - AI for Healthcare, Physiological Time-Series, Wearable Sensing, Continuous Glucose Monitoring, and Speech-Based Neurological Assessment"

url                      : "https://drkashifhon.github.io"
baseurl                  : ""
repository               : "drkashifhon/drkashifhon.github.io"


# Site Author
author:
  avatar           : "profile.jpg"
  name             : "Muhammad Kashif"
  bio              : "PhD Researcher in AI for Healthcare"
  location         : "Italy"
  employer         : "University of Calabria"
  uri              : "https://dottorato.dimes.unical.it/index.php/students/kashif-muhammad"
  email            : "kashif.muhammad@dimes.unical.it"

  # Academic profiles
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=z_kspJAAAAAJ"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0000-0002-5170-8004"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     : "https://www.researchgate.net/profile/Muhammad-Kashif-183"
  scopus           :
  zotero           :

  # Repositories
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "drkashifhon"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "kashifhon"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
